In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np

In [6]:
np.__version__

'1.23.5'

In [8]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)

numpy.ndarray

In [13]:
b=np.array([1,5,"a","c",31.5,False,"Roopa"])
b

array(['1', '5', 'a', 'c', '31.5', 'False', 'Roopa'], dtype='<U32')

In [14]:
type(b)

numpy.ndarray

In [15]:
a.shape

(5,)

In [16]:
b.shape

(7,)

In [17]:
c=np.array([3,5,7,9])
d=np.array([2,4,6,8])

z=c+d
print(z)

array([ 5,  9, 13, 17])

In [18]:
a=np.array(11)
print(a)


11


In [19]:
a.dtype
a

array(11)

In [20]:
a.ndim


0

In [21]:
#matrix
arr = np.array([[1, 2, 3], [4, 5, 6], [8, 9, 16],[21, 19, 316]])
print(arr)

[[  1   2   3]
 [  4   5   6]
 [  8   9  16]
 [ 21  19 316]]


In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.dtype

dtype('int32')

In [24]:
arr.ndim

2

In [25]:
arr.shape

(4, 3)

In [26]:
arr.size

12

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
a.shape

(3, 4)

In [34]:
a.size

12

In [36]:
a.dtype

dtype('float64')

In [37]:
a.ndim

2

In [38]:
my_matrix = [
             [1,2,3,14],
             [4,5,6,12],
             [7,8,9,34],
             [7,8,9,45]     
            ]
print(my_matrix)

[[1, 2, 3, 14], [4, 5, 6, 12], [7, 8, 9, 34], [7, 8, 9, 45]]


In [40]:
b=np.array(my_matrix)
b

array([[ 1,  2,  3, 14],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 34],
       [ 7,  8,  9, 45]])

In [41]:
b.shape

(4, 4)

In [42]:
b.size

16

In [43]:
b.dtype

dtype('int32')

In [44]:
b.ndim

2

In [45]:
#Tensor

# Create a tensor of shape (2, 3, 4)
tensor = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [47]:
tensor.shape

(2, 3, 4)

In [48]:
tensor.size

24

In [49]:
tensor.ndim

3

In [50]:
# (start,end-1,jump)#Arrange Syntax
a=np.arange(3,30)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
b=np.arange(2,40,5)
b

array([ 2,  7, 12, 17, 22, 27, 32, 37])

In [54]:
b.dtype

dtype('int32')

In [55]:
np.ones(12,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#np.linspace(start,end,no_of_items)
#logic
#interval=(end-start)/no_of_items

In [58]:
a=np.linspace(12,100,11)
a

array([ 12. ,  20.8,  29.6,  38.4,  47.2,  56. ,  64.8,  73.6,  82.4,
        91.2, 100. ])

In [59]:
a=np.linspace(55,250,11)
a

array([ 55. ,  74.5,  94. , 113.5, 133. , 152.5, 172. , 191.5, 211. ,
       230.5, 250. ])

In [60]:
a=np.eye(8)#creates a identity matrix
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
#rand
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(20)  

array([0.33053673, 0.35296179, 0.40138704, 0.35193236, 0.41067451,
       0.16708498, 0.33472272, 0.07534125, 0.38565242, 0.36849776,
       0.99058033, 0.50696055, 0.92402138, 0.11281633, 0.96527659,
       0.76814534, 0.46609929, 0.30215534, 0.43313926, 0.84014846])

In [62]:
np.random.rand(3,2)

array([[0.74327478, 0.26052989],
       [0.10877483, 0.51473972],
       [0.95408721, 0.19489847]])

In [63]:
#randn
#Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
np.random.randn(10)

array([-0.67609219, -0.59371593,  0.18062214,  0.73675291, -1.34526076,
       -0.70640199,  0.66159868,  0.85535117, -0.51387149,  0.71804463])

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
a=np.random.randint(21,100,15)
a

array([87, 62, 43, 86, 83, 56, 84, 93, 89, 47, 47, 90, 48, 79, 91])

In [66]:
a=np.random.randint(18,290,size=(2,3))
a

array([[153, 100, 220],
       [ 90,  55, 187]])

In [67]:
np.random.uniform(34.22)

18.858378941330734

In [68]:
arr=np.random.uniform(34.22,145.10,9)
arr

array([ 97.2599231 , 128.47385415,  78.15529618,  43.00030837,
        52.90524856, 110.196405  ,  89.22757818,  83.76934521,
        79.50812597])

In [69]:
arr=np.random.uniform(34.22,145.10,size=(3,2,3))
arr

array([[[105.00588683,  47.59605122, 108.43948432],
        [ 76.14994112, 101.60009943, 104.34782159]],

       [[ 90.51901719,  66.59173999, 101.82956286],
        [ 80.99994979, 138.56636188, 108.2005221 ]],

       [[ 79.57485254, 144.324767  , 134.9918783 ],
        [116.66990578,  86.92689922,  72.58056238]]])

In [70]:
arr=np.round(arr,1)
arr

array([[[105. ,  47.6, 108.4],
        [ 76.1, 101.6, 104.3]],

       [[ 90.5,  66.6, 101.8],
        [ 81. , 138.6, 108.2]],

       [[ 79.6, 144.3, 135. ],
        [116.7,  86.9,  72.6]]])

In [74]:
arr=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24,25,26,27,28,29])

In [75]:
arr.shape

(30,)

In [77]:
arr1=arr.reshape(5,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [78]:
arr1.ndim

2

In [79]:
np.average(arr)

14.5

In [80]:
sum(arr)

435

In [81]:
min(arr)

0

In [82]:
max(arr)

29

In [83]:
arr.argmax()

29

In [84]:
arr.argmin()

0

In [11]:
import numpy as np

my_arr=np.array([1,2,3,4,5])
my_arr

array([1, 2, 3, 4, 5])

In [23]:
a=np.array([2,3,4,5,6,])
a

array([2, 3, 4, 5, 6])

In [24]:
type(my_arr)

numpy.ndarray

In [14]:
my_arr.shape

(5,)

In [15]:
my_arr.size

5

In [26]:
new_arr=my_arr+a
new_arr

array([ 3,  5,  7,  9, 11])

In [21]:
a.reshape
a

array([2, 3, 4, 5, 6, 3])